### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by TridevGuha**
json object returned in #24

### CODE REVIEW

**Comment by ralphbean** [comment]
I'm confused about this change.  Can you explain the reasoning behind it?

**Comment by TridevGuha** [comment]
oops i think issue number was wrong

**Comment by pypingou** [comment]
@TridevGuha did you see @ralphbean's question?

**Comment by ralphbean** [comment]
I'm pretty sure that returning a ``str`` from ``strip_tags(...)`` instead of a dict is not what we want to do.  So, I'm going to close this.  @TridevGuha, if you want to explain and re-open it, feel free!

**Comment by TridevGuha** [comment]
OK @ralphbean  , I just returned the json object.

**Comment by ralphbean** [comment]
``json.dumps`` returns a string in python.  Any other code that previously called that function and tried to work with the return value would probably stop working.  Before it was returning a ``dict`` and now it would be returning a ``str`` -- those things behave quite differently.

**Comment by TridevGuha** [comment]
@ralphbean thanks, I will try to know more about it

**Pull request closed without merging**
